<?php
namespace Modules\Animals\Controllers;

use Carbon\Carbon;
use ICal\ICal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalDate;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Hotel\Models\Hotel;

class AvailabilityController extends FrontendController{

    protected $animalClass;
    /**
     * @var AnimalDate
     */
    protected $animalDateClass;

    /**
     * @var Booking
     */
    protected $bookingClass;

    protected $indexView = 'Animal::frontend.user.availability';

    public function __construct(Animal $animalClass, AnimalDate  $animalDateClass, Booking $bookingClass)
    {
        parent::__construct();
        $this->animalClass = $animalClass;
       $this->animalDateClass = $animalDateClass;
        $this->bookingClass = $bookingClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request){
        $this->checkPermission('animal_create');

        $q = $this->animalClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        if(!$this->hasPermission('animal_manage_others')){
            $q->where('author_id',$this->currentUser()->id);
        }

        $userHotelId = get_user_hotel_id();
        if ($userHotelId) {
            $q->where('hotel_id', $userHotelId);
        }

        $q->orderBy('bc_animals.id','desc');

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Animals'),
                'url'  => route('animal.vendor.index')
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Animal Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request'));
    }

    public function loadDates(Request $request)
    {
        $rules = [
            'id' => 'required',
            'start' => 'required',
            'end' => 'required',
        ];
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return $this->sendError($validator->errors());
        }

        $animal = $this->animalClass::find($request->query('id'));
        if (!$animal) {
            return $this->sendError(__('Animal not found'));
        }

        $calendarStart = Carbon::parse($request->start)->startOfDay();
        $calendarEnd   = Carbon::parse($request->end)->endOfDay();

        $rows = $this->animalDateClass::query()
            ->where('target_id', $animal->id)
            ->where('end_date', '>=', $calendarStart)
            ->where('start_date', '<=', $calendarEnd)
            ->get();

        $events = [];

        foreach ($rows as $row) {
            $rowStart = Carbon::parse($row->start_date)->startOfDay();
            $rowEnd   = Carbon::parse($row->end_date)->startOfDay();

            for ($date = $rowStart; $date->lte($rowEnd); $date->addDay()) {

                $event = [
                    'id' => $row->id . '-' . $date->format('Ymd'),
                    'start' => $date->format('Y-m-d'),
                    'display' => 'background',
                    'backgroundColor' => '#27ae60',
                ];

                if (!$row->active) {
                    $event['title'] = 'Доступно';
                    $event['backgroundColor'] = '#fe2727';
                    $event['borderColor'] = '#fe2727';
                    $event['classNames'] = ['blocked-event'];
                } else {

                }

                $events[] = $event;
            }
        }

        return response()->json($events);
    }



    public function store(Request $request){

        $request->validate([
            'target_id'=>'required',
            'start_date'=>'required',
            'end_date'=>'required'
        ]);

        $car = $this->carClass::find($request->input('target_id'));
        $target_id = $request->input('target_id');

        if(empty($car)){
            return $this->sendError(__('Car not found'));
        }

        if(!$this->hasPermission('car_manage_others')){
            if($car->author_id != Auth::id()){
                return $this->sendError("You do not have permission to access it");
            }
        }

        $dayOfWeek =$request->input("day_of_week_select",[]);

        $postData = $request->input();
        $period = periodDate($request->input('start_date'),$request->input('end_date'));
        foreach ($period as $dt){
            $date = $this->carDateClass::where('start_date',$dt->format('Y-m-d'))->where('target_id',$target_id)->first();

            if(empty($date)){
                $date = new $this->carDateClass();
                $date->target_id = $target_id;
            }
            $postData['start_date'] = $dt->format('Y-m-d H:i:s');
            $postData['end_date'] = $dt->format('Y-m-d H:i:s');


            $date->fillByAttr([
                'start_date','end_date','price','number',
                'is_instant','active',
            ],$postData);

            if(empty($dayOfWeek)){
                $date->save();
            }elseif(in_array(date('N', strtotime($dt->format('Y-m-d H:i:s')) ),$dayOfWeek)){
                $date->save();
            }
        }

        return $this->sendSuccess([],__("Update Success"));

    }

    public function checkAvailability(): \Illuminate\Http\JsonResponse
    {
        $animal_id = \request('animal_id');
        $hotel_id = \request('hotel_id');
        $start_date = request('start_date');
        $adults = request('adults');

        if(\request()->input('firstLoad') == "false") {
            $rules = [
                'hotel_id'   => 'required',
                'start_date' => 'required:date_format:Y-m-d',
                'adults'     => 'required',
                'animal_id'     => 'required',
            ];
            $validator = \Validator::make(request()->all(), $rules);
            if ($validator->fails()) {
                return $this->sendError($validator->errors()->all());
            }

            if(empty($start_date)){
                return $this->sendError(__("Please select a date"));
            }
        }

        $range = AnimalDate::where('target_id', $animal_id)
            ->where('start_date', '<=', $start_date)
            ->where('end_date', '>=', $start_date)
            ->first();

        if (!$range) {
            return $this->sendError('На эту дату охота на это животное недоступна');
        }

        $animalBookedCount = Booking::where('object_model', 'animal')
            ->whereDate('start_date', '=', $start_date)
            ->where('hotel_id', $hotel_id)
            ->where('status', 'processing')
            ->count();

        $hotel = Hotel::find($hotel_id);
        $maxTotalHunts = (int) $hotel->max_hunts_per_day;

        if ($animalBookedCount + 1 > $maxTotalHunts) {
            return $this->sendError('На эту дату лимит охот на выбранное животное исчерпан');
        }
        return $this->sendSuccess(['available' => true]);
    }
}
