<?php
namespace Modules\Animals\Controllers;

use Carbon\Carbon;
use ICal\ICal;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;
use Modules\Animals\Models\Animal;
use Modules\Animals\Models\AnimalDate;
use Modules\Animals\Models\AnimalPricePeriod;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Hotel\Models\Hotel;

class OrganisationController extends FrontendController{

    protected $animalClass;
    /**
     * @var AnimalDate
     */
    protected $animalDateClass;

    /**
     * @var Booking
     */
    protected $bookingClass;

    protected $indexView = 'Animal::frontend.user.organisation';

    public function __construct(Animal $animalClass, AnimalDate  $animalDateClass, Booking $bookingClass)
    {
        parent::__construct();
        $this->animalClass = $animalClass;
        $this->animalDateClass = $animalDateClass;
        $this->bookingClass = $bookingClass;
    }

    public function callAction($method, $parameters)
    {
        if(!Animal::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
    public function index(Request $request){
        $this->checkPermission('animal_create_hunting');

        $q = $this->animalClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Animal'),
                'url'  => route('animal.vendor.index')
            ],
            [
                'name'  => __('Hunting organization'),
                'class' => 'active'
            ],
        ];
        $page_title = __('Hunting organization');

        return view('Animals::user.organisation',compact('rows','breadcrumbs','current_month','page_title','request'));
    }
    public function create($animalId)
    {
        $period = AnimalPricePeriod::create([
            'animal_id' => $animalId,
            'start_date' => null,
            'end_date' => null,
            'amount' => null,
        ]);

        $html = view('Animal::frontend.partials.period_row', [
            'period' => $period
        ])->render();

        return response()->json([
            'status' => true,
            'html'   => $html,
            'animal_id' =>$animalId,
        ]);
    }

    public function update(Request $request, AnimalPricePeriod $period)
    {
        $period->update([
            'start_date' => $request->start_date,
            'end_date'   => $request->end_date,
            'price'     => $request->amount,
        ]);

        return $this->sendSuccess([
            'message' => __("Saved Success")
        ]);
    }

    public function delete(AnimalPricePeriod $period)
    {
        $period->delete();

        return response()->json([
            'status' => true,
            'id' => $period->id
        ]);
    }
}
