<?php
namespace Modules\Hotel\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Modules\Booking\Models\Booking;
use Modules\FrontendController;
use Modules\Hotel\Models\Hotel;
use Modules\Hotel\Models\HotelRoom;
use Modules\Hotel\Models\HotelRoomBooking;
use Modules\Hotel\Models\HotelRoomDate;
use Modules\Hotel\Services\AddDataInView;

class AvailabilityController extends FrontendController{

    protected $roomClass;
    /**
     * @var HotelRoomDate
     */
    protected $roomDateClass;

    /**
     * @var Booking
     */
    protected $bookingClass;
    protected $hotelClass;
    protected $currentHotel;
    protected $roomBookingClass;

    protected ?AddDataInView $cabinetService;

    protected $indexView = 'Hotel::frontend.user.availability';

    public function __construct(AddDataInView $cabinetService)
    {
        if ($cabinetService) {
            parent::__construct();
        }
        $this->roomClass = HotelRoom::class;
        $this->roomDateClass = HotelRoomDate::class;
        $this->bookingClass = Booking::class;
        $this->hotelClass = Hotel::class;
        $this->roomBookingClass = HotelRoomBooking::class;
        $this->cabinetService = $cabinetService;
    }
    public function callAction($method, $parameters)
    {
        if(!Hotel::isEnable())
        {
            return redirect('/');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }

    protected function hasHotelPermission($hotel_id = false){
        if(empty($hotel_id)) return false;

        $hotel = $this->hotelClass::find($hotel_id);
        if(empty($hotel)) return false;

        if(!$this->hasPermission('hotel_update') and $hotel->author_id != Auth::id()){
            return false;
        }

        $this->currentHotel = $hotel;
        return true;
    }

    public function index(Request $request,$hotel_id)
    {
        $this->checkPermission('hotel_update');
        $user = $this->cabinetService->getViewUser();
        $viewAdminCabinet = $this->cabinetService->getCabinetData();

        if(!$this->hasHotelPermission($hotel_id))
        {
            abort(403);
        }

        $q = $this->roomClass::query();

        if($request->query('s')){
            $q->where('title','like','%'.$request->query('s').'%');
        }

        $q->orderBy('id','desc');
        $q->where('parent_id',$hotel_id);

        $rows = $q->paginate(15);

        $current_month = strtotime(date('Y-m-01',time()));

        if($request->query('month')){
            $date = date_create_from_format('m-Y',$request->query('month'));
            if(!$date){
                $current_month = time();
            }else{
                $current_month = $date->getTimestamp();
            }
        }
        $breadcrumbs = [
            [
                'name' => __('Hotels'),
                'url'  => route('hotel.vendor.index')
            ],
            [
                'name' => __('Hotel::name',['name'=>$this->currentHotel->title]),
                'url'  => route('hotel.vendor.edit',[$this->currentHotel->id])
            ],
            [
                'name'  => __('Availability'),
                'class' => 'active'
            ],
        ];
        $hotel = $this->currentHotel;
        $page_title = __('Room Availability');

        return view($this->indexView,compact('rows','breadcrumbs','current_month','page_title','request','hotel', 'user', 'viewAdminCabinet'));
    }

//    public function loadDates(Request $request,$hotel_id)
//    {
//        $request->validate([
//            'id' => 'required',
//            'start' => 'required',
//            'end' => 'required',
//        ]);
//
//        if (!$this->hasHotelPermission($hotel_id)) {
//            return $this->sendError(__("Hotel not found"));
//        }
//
//        $room = $this->roomClass::find($request->query('id'));
//
//        if (empty($room)) {
//            return $this->sendError(__('room not found'));
//        }
//
//        $is_single = $request->query('for_single');
//
//        $query = $this->roomDateClass::query();
//
//        $query->where('target_id', $request->query('id'));
//        $query->where('start_date', '>=', date('Y-m-d H:i:s', strtotime($request->query('start'))));
//        $query->where('end_date', '<=', date('Y-m-d H:i:s', strtotime($request->query('end'))));
//
//        $rows = $query->take(100)->get();
//
//
//        $allDates = [];
//
//        $period = periodDate($request->input('start'), $request->input('end'), false);
//
//        foreach ($period as $dt) {
//            $date = [
//                'id' => rand(0, 999),
//                'active' => 0,
//                'price' => $room->price,
//                'number' => $room->number,
//                'is_instant' => 0,
//                'is_default' => true,
////                'textColor' => '#2791fe'
//                'extendedProps' => [
//                    'max_number' => 6,
//                ],
//            ];
//            $date['price_html'] = format_money($date['price']);
//            if (!$is_single) {
//                $date['price_html'] = format_money_main($date['price']);
//            }
//            $date['title'] = $date['event'] = $date['price_html'] . ' x ' . $room->number;
//            $date['start'] = $date['end'] = $dt->format('Y-m-d');
//
//            $date['active'] = 1;
//            $allDates[$dt->format('Y-m-d')] = $date;
//        }
//
//        //Тут получаем доступные номера из таблицы bc_hotel_dates
//        if (!empty($rows)) {
//            foreach ($rows as $row) {
//                $row->start = date('Y-m-d', strtotime($row->start_date));
//                $row->end = date('Y-m-d', strtotime($row->start_date));
////                $row->textColor = '#1A2B47';
//                $price = $row->price;
//                if (empty($price)) {
//                    $price = $room->price;
//                }
//                $row->title = $row->event = format_money($price);
////                if (!$is_single) {
////                    $row->title = $row->event = format_money_main($price) . ' x ' . $row->number;
////                }
//                $row->price = $price;
//
//                if (!$row->active) {
//                    $row->title = $row->event = __('Blocked');
//                    $row->classNames = ['blocked-event'];
//                    $row->active = 0;
//                } else {
//                    $row->classNames = ['available-event'];
//                    $row->active = 1;
////                    if($row->is_instant){
////                        $row->title = '<i class="fa fa-bolt"></i> '.$row->title;
////                    }
//                }
//
//                $allDates[date('Y-m-d', strtotime($row->start_date))] = $row->toArray();
//
//            }
//        }
//        $bookings = $room->getBookingsInRange($request->query('start'), $request->query('end'));
//
//        foreach ($bookings as $roomBooking) {
//            $period = periodDate($roomBooking->start_date, $roomBooking->end_date, false);
//
//            $booking = Booking::find($roomBooking->booking_id);
//            if (!$booking) continue;
//            $totalGuests = $booking->total_guests ?? 0;
//
//            foreach ($period as $dt) {
//                $date = $dt->format('Y-m-d');
//                if (!isset($allDates[$date])) continue;
//
//                if (!isset($allDates[$date]['booking_ids'])) {
//                    $allDates[$date]['booking_ids'] = [];
//                }
//
//                if (!isset($allDates[$date]['bookings'])) {
//                    $allDates[$date]['bookings'] = [];
//                }
//
//                $allDates[$date]['bookings'][] = [
//                    'id' => $booking->id
//                ];
//
//                if (!isset($allDates[$date]['occupiedBeds'])) {
//                    $allDates[$date]['occupiedBeds'] = 0;
//                }
//
//                $allDates[$date]['occupiedBeds'] += $totalGuests;
//
//                $totalBeds = $room->number * $room->beds;
//                $remainingBeds = max($totalBeds - $allDates[$date]['occupiedBeds'], 0);
//
//                $requestedGuests = $request->query('adults') ?? 1;
//                if ($remainingBeds < $requestedGuests) {
//                    $allDates[$date]['active'] = 0;
//                    $allDates[$date]['number'] = 0;
//                    $allDates[$date]['price'] = $allDates[$date]['price'] ?? 0;
//                    $allDates[$date]['classNames'] = ['full-book-event'];
//                } else {
//                    $allDates[$date]['active'] = 1;
//                    $allDates[$date]['number'] = $remainingBeds;
//                    $allDates[$date]['price'] = $allDates[$date]['price'] ?? 0;
//                    $allDates[$date]['classNames'] = ['available-event'];
//                }
//            }
//        }
//
//// Генерируем отдельный HTML для брони (только ID)
//        foreach ($allDates as &$day) {
//            if (!empty($day['bookings'])) {
//                $bookingHtml = '<div class="calendar-bookings">';
//                foreach ($day['bookings'] as $b) {
//                    $bookingHtml .= '<div class="booking-item">#' . e($b['id']) . '</div>';
//                }
//                $bookingHtml .= '</div>';
//
//                $day['bookings_html'] = $bookingHtml;
//
//                // Оставляем title/event только для цены
//                $day['title'] = format_money_main($day['price']) . ' x ' . $day['number'];
//                $day['event'] = $day['title'];
//            }
//        }
//        unset($day);
//
//        $data = array_values($allDates);
//
//        return response()->json($data);
//    }

    public function loadDates(Request $request, $hotel_id)
    {
        $request->validate([
            'id' => 'required',
            'start' => 'required',
            'end' => 'required',
        ]);

        if (!$this->hasHotelPermission($hotel_id)) {
            return $this->sendError(__("Hotel not found"));
        }

        $room = $this->roomClass::find($request->query('id'));
        if (!$room) {
            return $this->sendError(__('room not found'));
        }

        $is_single = $request->query('for_single');

        /** ----------------------------------------
         * 1. Загружаем кастомные даты
         * ---------------------------------------- */
        $rows = $this->roomDateClass::query()
            ->where('target_id', $room->id)
            ->whereBetween('start_date', [
                date('Y-m-d 00:00:00', strtotime($request->query('start'))),
                date('Y-m-d 23:59:59', strtotime($request->query('end')))
            ])
            ->get()
            ->keyBy(fn ($row) => date('Y-m-d', strtotime($row->start_date)));

        /** ----------------------------------------
         * 2. Генерируем ВСЕ дни периода
         * ---------------------------------------- */
        $allDates = [];
        $period = periodDate($request->input('start'), $request->input('end'), false);

        foreach ($period as $dt) {
            $dateKey = $dt->format('Y-m-d');

            $allDates[$dateKey] = [
                'id' => uniqid(),
                'start' => $dateKey,
                'allDay' => true,

                'price' => $room->price,
                'number' => $room->number,
                'active' => 1,
                'extendedProps' => [
                    'max_number' => $room->number,
                ],
            ];

            $priceHtml = format_money($room->price);
            if (!$is_single) {
                $priceHtml = format_money_main($room->price);
            }

            $allDates[$dateKey]['title'] = $priceHtml . ' x ' . $room->number;
        }

        /** ----------------------------------------
         * 3. Мержим кастомные даты (НЕ затирая extendedProps)
         * ---------------------------------------- */
        foreach ($rows as $dateKey => $row) {
            $price = $row->price ?: $room->price;

            $existing = $allDates[$dateKey];

            $allDates[$dateKey] = array_merge(
                $existing,
                [
                    'price' => $price,
                    'number' => $row->number ?? $existing['number'],
                    'active' => (int) $row->active,
                    'classNames' => $row->active ? ['available-event'] : ['blocked-event'],
                    'title' => $row->active
                        ? format_money_main($price) . ' x ' . ($row->number ?? $existing['number'])
                        : __('Blocked'),
                ],
                [
                    // ✅ extendedProps СОХРАНЯЕМ
                    'extendedProps' => array_merge(
                        $existing['extendedProps'],
                        [
                            'max_number' => $room->number,
                        ]
                    ),
                ]
            );
        }

        /** ----------------------------------------
         * 4. Учитываем бронирования
         * ---------------------------------------- */
        $bookings = $room->getBookingsInRange(
            $request->query('start'),
            $request->query('end')
        );

        foreach ($bookings as $roomBooking) {
            $booking = Booking::find($roomBooking->booking_id);
            if (!$booking) continue;

            $period = periodDate(
                $roomBooking->start_date,
                $roomBooking->end_date,
                false
            );

            foreach ($period as $dt) {
                $dateKey = $dt->format('Y-m-d');
                if (!isset($allDates[$dateKey])) continue;

                $day = &$allDates[$dateKey];

                $day['bookings'][] = [
                    'id' => $booking->id,
                    'code' => $booking->code,
                    'status' => $booking->status,
                    'statusName' => $booking->statusName,
                ];

                $day['occupiedBeds'] = ($day['occupiedBeds'] ?? 0)
                    + ($booking->total_guests ?? 0);

                $totalBeds = $room->number * $room->beds;
                $freeBeds = max($totalBeds - $day['occupiedBeds'], 0);
                $freeRooms = floor($freeBeds / $room->beds);

                $requestedGuests = $request->query('adults') ?? 1;

                if ($freeBeds < $requestedGuests) {
                    $day['active'] = 0;
                    $day['number'] = 0;
                    $day['classNames'] = ['full-book-event'];
                } else {
                    $day['active'] = 1;
                    $day['number'] = 0;
                    $day['classNames'] = ['available-event'];
                }

                $day['title'] = format_money_main($day['price']) . ' x ' . $day['number'];
            }
        }

        /** ----------------------------------------
         * 5. HTML для броней
         * ---------------------------------------- */
        foreach ($allDates as &$day) {
            if (empty($day['bookings'])) { continue; }
            $bookingHtml = '<div class="calendar-bookings">';
            foreach ($day['bookings'] as $b) {
                $status = htmlspecialchars($b['status'] ?? '');
                $code = htmlspecialchars($b['code'] ?? '');
                $label = htmlspecialchars($b['statusName'] ?? '');
                $bookingHtml
                    .= '<div class="booking-item booking-status-' . $status . '">'
                    . '<span class="booking-id" data-id="' . (int)$b['id'] . '" data-code="' . e($b['code']) . '">'
                    . 'Б' . (int)$b['id'] .
                    '</span>'
                    . '<span class="booking-status">' . $label . '</span>' . '</div>'; }

            $bookingHtml .= '</div>';
            $day['bookings_html'] = $bookingHtml;
        }
        unset($day);

        /** ----------------------------------------
         * 6. Отдаём в FullCalendar
         * ---------------------------------------- */
        return response()->json(array_values($allDates));
    }


//    public function loadDates(Request $request, $hotel_id)
//    {
//        $roomId = 72; // пример
//        $start = '2026-01-01';
//        $end = '2026-01-31';
//
//        $rows = $this->roomDateClass::query()
//            ->where('target_id', $roomId)
//            ->where('start_date', '>=', $start)
//            ->where('end_date', '<=', $end)
//            ->orderBy('start_date')
//            ->get();
//
//        dd($rows->toArray());
//        return $rows->toArray();
//    }




//    public function loadDates(Request $request, $hotel_id)
//    {
//        $request->validate([
//            'id'    => 'required',
//            'start' => 'required',
//            'end'   => 'required',
//        ]);
//
//        if (!$this->hasHotelPermission($hotel_id)) {
//            return $this->sendError(__("Hotel not found"));
//        }
//
//        /** @var HotelRoom $room */
//        $room = $this->roomClass::find($request->query('id'));
//        if (!$room) {
//            return $this->sendError(__('room not found'));
//        }
//
//        $is_single = $request->query('for_single');
//        $requestedGuests = (int)($request->query('adults') ?? 1);
//
//        /* ------------------------------------------------------------
//         | 1. БАЗОВЫЕ ДНИ КАЛЕНДАРЯ (НИКАКОЙ ОКРАСКИ)
//         * ------------------------------------------------------------ */
//        $allDates = [];
//        $period = periodDate($request->input('start'), $request->input('end'), false);
//
//        foreach ($period as $dt) {
//            $dateKey = $dt->format('Y-m-d');
//            $totalBeds = $room->number * $room->beds;
//            $price = $room->price;
//
//            $priceHtml = $is_single
//                ? format_money($price)
//                : format_money_main($price);
//
//            $allDates[$dateKey] = [
//                'id'            => rand(1000, 9999),
//                'start'         => $dateKey,
//                'end'           => $dateKey,
//                'price'         => $price,
//                'number'        => $totalBeds,
//                'active'        => 1,
//                'textColor'     => '#2791fe',
//                'title'         => $priceHtml . ' x ' . $totalBeds,
//                'event'         => $priceHtml . ' x ' . $totalBeds,
//                'bookings'      => [],
//                'occupiedBeds' => 0,
//                // classNames НЕТ
//            ];
//        }
//
//        /* ------------------------------------------------------------
//         | 2. БЛОКИРОВКИ (RoomDate)
//         * ------------------------------------------------------------ */
//        $rows = $this->roomDateClass::query()
//            ->where('target_id', $room->id)
//            ->whereBetween('start_date', [
//                date('Y-m-d H:i:s', strtotime($request->query('start'))),
//                date('Y-m-d H:i:s', strtotime($request->query('end')))
//            ])
//            ->get();
//
//        foreach ($rows as $row) {
//            $dateKey = date('Y-m-d', strtotime($row->start_date));
//            if (!isset($allDates[$dateKey])) continue;
//
//            if (!$row->active) {
//                $allDates[$dateKey]['active'] = 0;
//                $allDates[$dateKey]['classNames'] = ['blocked-event'];
//                $allDates[$dateKey]['title'] = __('Blocked');
//                $allDates[$dateKey]['event'] = __('Blocked');
//                $allDates[$dateKey]['textColor'] = '#fe2727';
//            }
//        }
//
//        /* ------------------------------------------------------------
//         | 3. БРОНИ
//         | 3.1 UI: показываем бронь НА КАЖДЫЙ ДЕНЬ (включая выезд)
//         | 3.2 Capacity: считаем койки ТОЛЬКО до дня выезда
//         * ------------------------------------------------------------ */
//        $bookings = $room->getBookingsInRange(
//            $request->query('start'),
//            $request->query('end')
//        );
//
//        foreach ($bookings as $roomBooking) {
//            $booking = Booking::find($roomBooking->booking_id);
//            if (!$booking) continue;
//
//            $guests = (int)($booking->total_guests ?? 0);
//
//            // 🔹 Дни отображения (включая выезд)
//            $uiPeriod = periodDate(
//                $roomBooking->start_date,
//                $roomBooking->end_date,
//                true // включаем день выезда
//            );
//
//            // 🔹 Дни проживания (без выезда)
//            $stayPeriod = periodDate(
//                $roomBooking->start_date,
//                $roomBooking->end_date,
//                false
//            );
//
//            // UI
//            foreach ($uiPeriod as $dt) {
//                $dateKey = $dt->format('Y-m-d');
//                if (!isset($allDates[$dateKey])) continue;
//
//                $allDates[$dateKey]['bookings'][] = [
//                    'id' => $booking->id,
//                ];
//            }
//
//            // Capacity
//            foreach ($stayPeriod as $dt) {
//                $dateKey = $dt->format('Y-m-d');
//                if (!isset($allDates[$dateKey])) continue;
//
//                $allDates[$dateKey]['occupiedBeds'] += $guests;
//            }
//        }
//
//        /* ------------------------------------------------------------
//         | 4. ФИНАЛ: ОКРАСКА ТОЛЬКО ПО ФАКТУ
//         * ------------------------------------------------------------ */
//        foreach ($allDates as &$day) {
//            $remainingBeds = max($day['number'] - $day['occupiedBeds'], 0);
//
//            if ($remainingBeds < $requestedGuests) {
//                $day['active'] = 0;
//                $day['number'] = 0;
//                $day['classNames'] = ['full-book-event'];
//            } elseif (!empty($day['bookings'])) {
//                $day['number'] = $remainingBeds;
//                $day['classNames'] = ['has-booking-event'];
//            } else {
//                unset($day['classNames']);
//            }
//
//            if (!empty($day['bookings'])) {
//                $html = '<div class="calendar-bookings">';
//                foreach ($day['bookings'] as $b) {
//                    $html .= '<div class="booking-item">#' . e($b['id']) . '</div>';
//                }
//                $html .= '</div>';
//                $day['bookings_html'] = $html;
//            }
//
//            $day['title'] = format_money_main($day['price']) . ' x ' . $day['number'];
//            $day['event'] = $day['title'];
//        }
//        unset($day);
//
//        return response()->json(array_values($allDates));
//    }



    public function store(Request $request,$hotel_id)
    {
        if(!$this->hasHotelPermission($hotel_id))
        {
            return $this->sendError(__("Hotel not found"));
        }

        $request->validate([
            'target_id'=>'required',
            'start_date'=>'required',
            'end_date'=>'required'
        ]);

        $room = $this->roomClass::find($request->input('target_id'));
        $target_id = $request->input('target_id');

        if(empty($room)){
            return $this->sendError(__('Room not found'));
        }

        if(!$this->hasPermission('hotel_manage_others')){

            if($this->currentHotel->author_id != Auth::id()){
                return $this->sendError("You do not have permission to access it");
            }
        }

        $dayOfWeek =$request->input("day_of_week_select",[]);

        $postData = $request->input();
        $period = periodDate($request->input('start_date'),$request->input('end_date'));
        foreach ($period as $dt){
            $date = $this->roomDateClass::where('start_date',$dt->format('Y-m-d'))->where('target_id',$target_id)->first();

            if(empty($date)){
                $date = new $this->roomDateClass();
                $date->target_id = $target_id;
            }
            $postData['start_date'] = $dt->format('Y-m-d H:i:s');
            $postData['end_date'] = $dt->format('Y-m-d H:i:s');

            $date->fillByAttr([
                'start_date','end_date','price',
                'is_instant','active',
                'number'
            ],$postData);

            if(empty($dayOfWeek)){
                $date->save();
            }elseif(in_array(date('N', strtotime($dt->format('Y-m-d H:i:s')) ),$dayOfWeek)){
                $date->save();
            }
        }

        return $this->sendSuccess([],__("Update Success"));
    }
}
